//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.04 at 06:08:30 下午 CST
//

package com.zizhizhan.legacies.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Address_QNAME = new QName("", "address");
	private final static QName _Customer_QNAME = new QName("", "customer");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: generated
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Customer }
	 * 
	 */
	public Customer createCustomer() {
		return new Customer();
	}

	/**
	 * Create an instance of {@link Address }
	 * 
	 */
	public Address createAddress() {
		return new Address();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Address }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "address")
	public JAXBElement<Address> createAddress(Address value) {
		return new JAXBElement<Address>(_Address_QNAME, Address.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Customer }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "customer")
	public JAXBElement<Customer> createCustomer(Customer value) {
		return new JAXBElement<Customer>(_Customer_QNAME, Customer.class, null, value);
	}

}
